'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34003
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MCARuntime.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nürburgring 0.1.11.5
        '''-Versión inicial
        '''
        '''Nürburgring 0.2.0.10
        '''-Primer implementación de concepto de plugins
        '''-Corregido un problema con VMRunner al finalizar una máquina virtual
        '''-Corregida parcialmente la inoperatibilidad de Bintools2
        '''-Desactivación de código no compilable (DUFParser v1.0)
        '''
        '''Nürburgring 0.2.0.11
        '''-Cambios menores
        '''
        '''Nürburgring 0.2.1.12
        '''-Corregidos problemas de estabilidad al cargar Plugins
        '''-Más correcciones a la inoperatibilidad de Bintools2
        '''-Reactivación de DUFParser v1.0 mediante [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Changes() As String
            Get
                Return ResourceManager.GetString("Changes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -=&lt; MCA RUNTIME &gt;=-
        '''
        '''-{Progrmación general}-
        '''	César Andrés Morgan
        '''
        '''-{Diseño de formularios}-
        '''	César Andrés Morgan
        '''
        '''-{Gráficos}-
        '''	César Andrés Morgan
        '''
        '''-{Pruebas de la rutina}-
        '''	César Morgan
        '''	Gerardo Belot
        '''
        '''-= MCA Bintools =-
        '''Rutina extraída y reescrita de &quot;XDS!SUBS&quot; por César Morgan.
        '''
        '''-= Bintools 2 =-
        '''César Andrés Morgan
        '''
        '''-= DUFParser =-
        '''-{Formato de archivo DUF}-
        '''	César Andrés Morgan
        '''-{Sistema de Encritación AES}
        '''	Utilizado bajo licencia GNU/GPL
        '''	Rutinas .NET - Microsoft
        '''	Implemen [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Credits() As String
            Get
                Return ResourceManager.GetString("Credits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MCARuntime main DLL.
        '''</summary>
        Friend ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nota legal algo extensa de ejemplo
        '''Esta nota demuestra qué tanto espacio podría ocupar una nota legal verdadera. Se usa este texto, porque aún no se ha cubierto el código fuente de este Runtime bajo ninguna licencia, más que tal vez el uso de este programa para fines no-comerciales. Supongo, que de todas maneras, habría que traducir este archivo a varios idiomas, pero esa es otra historia.
        '''DUF (Data of Usuers File) es propiedad de César Andrés Morgan. Formato de archivo Pendiente de patente..
        '''</summary>
        Friend ReadOnly Property LegalNote() As String
            Get
                Return ResourceManager.GetString("LegalNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MCARuntime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MCARuntime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property MCARuntime1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MCARuntime1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property Plugin() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Plugin", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
